const roles = [
  { role: 'GET_DOCTOR' },
  { role: 'GET_DOCTORS' },
  { role: 'CREATE_DOCTOR' },
  { role: 'UPDATE_DOCTOR' },
  { role: 'GET_GUIDE' },
  { role: 'GET_GUIDES' },
  { role: 'CREATE_GUIDE' },
  { role: 'UPDATE_GUIDE' },
  { role: 'GET_PATIENT' },
  { role: 'GET_PATIENTS' },
  { role: 'CREATE_PATIENT' },
  { role: 'UPDATE_PATIENT' },
  { role: 'GET_PROCEDURE_TABLE' },
  { role: 'GET_PROCEDURE_TABLES' },
  { role: 'CREATE_PROCEDURE_TABLE' },
  { role: 'UPDATE_PROCEDURE_TABLE' },
  { role: 'GET_PROCEDURE' },
  { role: 'GET_PROCEDURES' },
  { role: 'CREATE_PROCEDURE' },
  { role: 'UPDATE_PROCEDURE' },
  { role: 'GET_SPECIALTY' },
  { role: 'GET_SPECIALTIES' },
  { role: 'CREATE_SPECIALTY' },
  { role: 'UPDATE_SPECIALTY' },
];

export default roles;
